name: 'Setup Node.js Project'
description: 'Sets up Node.js, installs dependencies, and generates Prisma client'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  working-directory:
    description: 'Working directory for npm operations'
    required: false
    default: '.'
  generate-prisma:
    description: 'Whether to generate Prisma client'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Generate Prisma Client
      if: inputs.generate-prisma == 'true'
      shell: bash
      working-directory: ./apps/api-gateway
      run: npx prisma generate
