/**
 * Audit Log Types
 * Defines event types and structures for audit logging
 */

/**
 * Event types for audit logging
 * Organized by category
 */
export enum AuditEventType {
  // Authentication Events
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH',
  AUTH_PASSWORD_CHANGE = 'AUTH_PASSWORD_CHANGE',
  AUTH_PASSWORD_RESET_REQUEST = 'AUTH_PASSWORD_RESET_REQUEST',
  AUTH_PASSWORD_RESET_COMPLETE = 'AUTH_PASSWORD_RESET_COMPLETE',

  // Email Verification Events
  AUTH_EMAIL_VERIFICATION_SENT = 'AUTH_EMAIL_VERIFICATION_SENT',
  AUTH_EMAIL_VERIFICATION_SUCCESS = 'AUTH_EMAIL_VERIFICATION_SUCCESS',
  AUTH_EMAIL_VERIFICATION_FAILURE = 'AUTH_EMAIL_VERIFICATION_FAILURE',

  // Multi-Factor Authentication Events
  AUTH_MFA_ENABLED = 'AUTH_MFA_ENABLED',
  AUTH_MFA_DISABLED = 'AUTH_MFA_DISABLED',
  AUTH_MFA_VERIFIED = 'AUTH_MFA_VERIFIED',
  AUTH_MFA_FAILURE = 'AUTH_MFA_FAILURE',
  AUTH_MFA_BACKUP_CODE_USED = 'AUTH_MFA_BACKUP_CODE_USED',

  // User Management Events
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
  USER_PERMISSIONS_CHANGED = 'USER_PERMISSIONS_CHANGED',

  // Tenant Management Events
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_DELETED = 'TENANT_DELETED',
  TENANT_PLAN_CHANGED = 'TENANT_PLAN_CHANGED',
  TENANT_STATUS_CHANGED = 'TENANT_STATUS_CHANGED',

  // Cloud Account Events
  CLOUD_ACCOUNT_CREATED = 'CLOUD_ACCOUNT_CREATED',
  CLOUD_ACCOUNT_UPDATED = 'CLOUD_ACCOUNT_UPDATED',
  CLOUD_ACCOUNT_DELETED = 'CLOUD_ACCOUNT_DELETED',
  CLOUD_ACCOUNT_CREDENTIALS_UPDATED = 'CLOUD_ACCOUNT_CREDENTIALS_UPDATED',
  CLOUD_ACCOUNT_CONNECTED = 'CLOUD_ACCOUNT_CONNECTED',
  CLOUD_ACCOUNT_CONNECTION_FAILED = 'CLOUD_ACCOUNT_CONNECTION_FAILED',
  CLOUD_ACCOUNT_SYNC_STARTED = 'CLOUD_ACCOUNT_SYNC_STARTED',
  CLOUD_ACCOUNT_SYNC_COMPLETED = 'CLOUD_ACCOUNT_SYNC_COMPLETED',
  CLOUD_ACCOUNT_SYNC_FAILED = 'CLOUD_ACCOUNT_SYNC_FAILED',

  // API Key Events
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  API_KEY_USED = 'API_KEY_USED',

  // Security Events
  SECURITY_POLICY_CREATED = 'SECURITY_POLICY_CREATED',
  SECURITY_POLICY_UPDATED = 'SECURITY_POLICY_UPDATED',
  SECURITY_POLICY_DELETED = 'SECURITY_POLICY_DELETED',
  SECURITY_SCAN_STARTED = 'SECURITY_SCAN_STARTED',
  SECURITY_SCAN_COMPLETED = 'SECURITY_SCAN_COMPLETED',
  SECURITY_VIOLATION_DETECTED = 'SECURITY_VIOLATION_DETECTED',

  // Resource Events
  RESOURCE_DISCOVERED = 'RESOURCE_DISCOVERED',
  RESOURCE_UPDATED = 'RESOURCE_UPDATED',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  RESOURCE_TAG_CHANGED = 'RESOURCE_TAG_CHANGED',

  // Billing Events
  BILLING_SUBSCRIPTION_CREATED = 'BILLING_SUBSCRIPTION_CREATED',
  BILLING_SUBSCRIPTION_UPDATED = 'BILLING_SUBSCRIPTION_UPDATED',
  BILLING_SUBSCRIPTION_CANCELLED = 'BILLING_SUBSCRIPTION_CANCELLED',
  BILLING_PAYMENT_SUCCESS = 'BILLING_PAYMENT_SUCCESS',
  BILLING_PAYMENT_FAILED = 'BILLING_PAYMENT_FAILED',

  // Data Access Events
  DATA_EXPORT = 'DATA_EXPORT',
  DATA_IMPORT = 'DATA_IMPORT',
  SENSITIVE_DATA_ACCESSED = 'SENSITIVE_DATA_ACCESSED',

  // System Events
  SYSTEM_SETTINGS_CHANGED = 'SYSTEM_SETTINGS_CHANGED',
  SYSTEM_BACKUP_CREATED = 'SYSTEM_BACKUP_CREATED',
  SYSTEM_BACKUP_RESTORED = 'SYSTEM_BACKUP_RESTORED',
}

/**
 * Resource types that can be audited
 */
export enum AuditResourceType {
  USER = 'USER',
  TENANT = 'TENANT',
  CLOUD_ACCOUNT = 'CLOUD_ACCOUNT',
  API_KEY = 'API_KEY',
  SECURITY_POLICY = 'SECURITY_POLICY',
  RESOURCE = 'RESOURCE',
  SUBSCRIPTION = 'SUBSCRIPTION',
  SETTINGS = 'SETTINGS',
}

/**
 * Audit log severity levels
 */
export enum AuditSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

/**
 * Audit log entry structure
 */
export interface AuditLogEntry {
  tenantId: string;
  userId?: string;
  action: AuditEventType;
  resourceType?: AuditResourceType;
  resourceId?: string;
  ipAddress?: string;
  userAgent?: string;
  severity?: AuditSeverity;
  metadata?: Record<string, any>;
  success?: boolean;
  errorMessage?: string;
}

/**
 * Audit log filter for querying
 */
export interface AuditLogFilter {
  tenantId: string;
  userId?: string;
  action?: AuditEventType | AuditEventType[];
  resourceType?: AuditResourceType;
  resourceId?: string;
  startDate?: Date;
  endDate?: Date;
  severity?: AuditSeverity;
  success?: boolean;
  limit?: number;
  offset?: number;
}

/**
 * Audit log query result
 */
export interface AuditLogResult {
  logs: AuditLogEntry[];
  total: number;
  hasMore: boolean;
}
